# Generated by Django 4.2.7 on 2023-11-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("subject", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("fees", models.IntegerField()),
                ("course_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_image", models.FileField(upload_to="media")),
                ("event_date", models.IntegerField()),
                ("event_month", models.CharField(max_length=50)),
                ("event_cordinator", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("event_title", models.CharField(max_length=100)),
                ("event_description", models.TextField()),
                ("event_points", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faq_question", models.CharField(max_length=300)),
                ("faq_answer", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="OurFacualty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facualty_image",
                    models.FileField(blank=True, null=True, upload_to="media"),
                ),
                (
                    "facualty_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "facualty_position",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("instagram", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("testimonial_content", models.CharField(max_length=300)),
                ("position", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CourseFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_feature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.course",
                    ),
                ),
            ],
        ),
    ]
