# Generated by Django 4.2.7 on 2023-11-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_course_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="month",
            new_name="duaration",
        ),
        migrations.AddField(
            model_name="course",
            name="course_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
