# Generated by Django 4.2.7 on 2023-11-25 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rename_month_course_duaration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="duaration",
            new_name="duration",
        ),
    ]
