# Generated by Django 4.2.7 on 2023-11-25 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_courseregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseregistration",
            name="message",
        ),
    ]
