# Generated by Django 4.2.7 on 2023-11-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_remove_courseregistration_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.course",
            ),
        ),
    ]
