# Generated by Django 4.2.7 on 2023-12-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_courseregistration_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_points",
        ),
        migrations.CreateModel(
            name="EventPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_points",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.event",
                    ),
                ),
            ],
        ),
    ]
