# Generated by Django 4.2.7 on 2023-12-02 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_remove_event_event_points_eventpoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.event",
            ),
        ),
    ]
